db:
  image: mysql
  volumes:
    - /root/blog_alura/database/:/var/lib/mysql/
  environment:
    - MYSQL_ROOT_PASSWORD=test123
blog:
  image: wordpress
  environment:
    - WORDPRESS_DB_PASSWORD=test123
  links:
    - db:mysql
  ports:
    - 80:80
